# Generated by Django 2.1 on 2018-08-06 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabDemos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_demos', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LabSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_time', models.TimeField(verbose_name='Time Chosen')),
                ('lab_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='labdemos',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminView.LabSlot'),
        ),
    ]
